source 'https://rubygems.org'
ruby '2.0.0'

#gem 'bandcamp-rb', :git => 'git@bitbucket.org:dekz/bandcamp-rb.git'
gem 'bandcamp_api', :git => 'https://github.com/dekz/bandcamp_api.git'
gem 'sinatra'
gem 'pry'
gem 'pry-remote'
gem 'pry-byebug'
gem 'foreman'
gem 'haml'
gem 'coffee-script'
gem 'thin'

gem 'datamapper', :require => 'data_mapper'
gem 'dm-sqlite-adapter'
